# Generated by Django 4.1.3 on 2022-11-10 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='employees',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ename', models.CharField(max_length=88)),
                ('eno', models.IntegerField()),
                ('eid', models.IntegerField()),
                ('email', models.CharField(max_length=99)),
            ],
        ),
    ]
